// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using maisAgua.Infrastructure.Context;

#nullable disable

namespace maisAgua.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("maisAgua.Domain.Devices.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_hora");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nome_dispositivo");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tbl_sensores", (string)null);
                });

            modelBuilder.Entity("maisAgua.Domain.Persistence.Readings.Reading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdDevice")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_sensor");

                    b.Property<int>("LevelPct")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("nivel_pct");

                    b.Property<float>("PhLevel")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("ph_int");

                    b.Property<DateTime>("ReadingDatetime")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_hora_leitura");

                    b.Property<float>("TurbidityNtu")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("turbidez_ntu");

                    b.HasKey("Id");

                    b.HasIndex("IdDevice");

                    b.ToTable("tbl_leituras", (string)null);
                });

            modelBuilder.Entity("maisAgua.Domain.Persistence.Readings.Reading", b =>
                {
                    b.HasOne("maisAgua.Domain.Devices.Device", "AssociatedDevice")
                        .WithMany("Readings")
                        .HasForeignKey("IdDevice")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssociatedDevice");
                });

            modelBuilder.Entity("maisAgua.Domain.Devices.Device", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
